### PR TITLE
Remove YAML Converter

### PR DESCRIPTION
**Pull request by DanInci**
Remove YAML converter and leave only LinkML converter in the codebase

### CODE REVIEW

**Review by imallona — APPROVED** [review]

**Comment by almutlue** [comment]
__Suggestion__: 
I think ideally the converter class would be removed as a whole and the `Benchmark` class has a model attribute that provides the `omnischema.model.Benchmark`. This would be one layer of nesting less and more readable. I know this requires much more refactoring, but I think it will pay off in future.  e.g.:

```
class Benchmark:
    def __init__(self, 
                 bench_yaml: Path, 
                 out_dir: str ='out'):
        
        self.model = dict_from_yaml(bench_yaml)
        self.out_dir = out_dir
```

**Comment by imallona** [comment]
No strong opinion about :point_up: but related. I'm sort of conflicted with the YAML parsing, I still think we'd be better off with a LinkML-free YAML parsing. The dependency, and https://github.com/omnibenchmark/omni-schema, seem too large to me to parse an uncomplicated YAML. Perhaps we could make things slimmer in future iterations, both abstraction-wise and tool-wise? Happy to discuss anytime

**Comment by DanInci** [comment]
> No strong opinion about ☝️ but related. I'm sort of conflicted with the YAML parsing, I still think we'd be better off with a LinkML-free YAML parsing. The dependency, and https://github.com/omnibenchmark/omni-schema, seem too large to me to parse an uncomplicated YAML. Perhaps we could make things slimmer in future iterations, both abstraction-wise and tool-wise? Happy to discuss anytime

I agree with this, for now LinkML provides a lot of out-of-the-box validations and parsing for us. Maybe when we'll have a stable schema, we could implement our own parser. But currently LinkML saves a lot of development effort.

**Comment by DanInci** [comment]
> **Suggestion**: I think ideally the converter class would be removed as a whole and the `Benchmark` class has a model attribute that provides the `omnischema.model.Benchmark`. This would be one layer of nesting less and more readable. I know this requires much more refactoring, but I think it will pay off in future. e.g.:
> 
> ```
> class Benchmark:
>     def __init__(self, 
>                  bench_yaml: Path, 
>                  out_dir: str ='out'):
>         
>         self.model = dict_from_yaml(bench_yaml)
>         self.out_dir = out_dir
> ```

Changed the `model.Benchmark` interface to be the same as the one you mentioned, although I kept the LinkMLConverter class, since it contains some logic that I find different than the one I expect in the Benchmark interface, e.g. computing the explicit vs implicit class, the order of stages and so on. 

Despite it introducing an additional layer of nestedness, I believe it will be useful in the future, in case we decide to swap the parser or model schema. This will maintain a decoupling between low-level parsing logic and higher-level benchmark model logic.

**Pull request merged**
